// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBse8d-ocnij08gFzzLISpVfzNX88jiBVA',
    appId: '1:646245280460:web:ada86f9cd69503c491b069',
    messagingSenderId: '646245280460',
    projectId: 'wedding-invitation-flutter',
    authDomain: 'wedding-invitation-flutter.firebaseapp.com',
    storageBucket: 'wedding-invitation-flutter.firebasestorage.app',
    measurementId: 'G-J0E3Z3ZK84',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAlXnKwBPDPiBBEx5COXMxE_IDHjRqShnM',
    appId: '1:646245280460:android:7f2eed9a9949218d91b069',
    messagingSenderId: '646245280460',
    projectId: 'wedding-invitation-flutter',
    storageBucket: 'wedding-invitation-flutter.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDh1CgItCxqmciUPUTjhPQush93TKg5zg0',
    appId: '1:646245280460:ios:40c8cbb8b623fb3991b069',
    messagingSenderId: '646245280460',
    projectId: 'wedding-invitation-flutter',
    storageBucket: 'wedding-invitation-flutter.firebasestorage.app',
    iosBundleId: 'com.soogil.boilerplate',
  );
}
